name: dragon_sword_purse
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 2.4.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter_localizations:
    sdk: flutter
  flutter:
    sdk: flutter
  flutter_screenutil: ^1.1.0
  image_picker: ^0.6.6+1
  photo_view: ^0.9.2
  cached_network_image: ^2.2.0+1
  web3dart: ^1.2.3
  hex: ^0.1.2
  ed25519_hd_key: ^1.0.1
  bip39: ^1.0.3
  shared_preferences: ^0.5.7+2
  sqflite: ^1.3.0+1
  fluttertoast: ^4.0.1
  dio: ^3.0.9
  loading_overlay: ^0.2.1
  date_format: ^1.0.8
  pull_to_refresh: ^1.5.8
  file_picker: ^1.9.0+1
  qr_flutter: ^3.2.0
  flutter_qr_reader: ^1.0.3
  permission_handler: ^5.0.0+hotfix.8
  image_gallery_saver: ^1.2.2
  web_socket_channel: ^1.1.0
  webview_flutter: ^0.3.22+1
  event_bus: ^1.1.1
  jpush_flutter: ^0.5.5
  common_utils: ^1.2.1
  path_provider: ^1.6.10
  rflutter_alert: ^1.0.3
  bot_toast: ^3.0.0
  uuid_enhanced: ^3.0.2
  flutter_local_notifications: ^1.4.4+1
  uni_links: ^0.4.0
  jmessage_flutter: ^0.6.3
  flutter_swiper: ^1.1.6
  package_info: ^0.4.1
  url_launcher: ^5.5.0
  pointycastle: ^1.0.2
  mobile_number: ^1.0.3
  simple_rsa2: ^0.0.7
  flutter_custom_calendar:
    git:
      url: https://github.com/LXD312569496/flutter_custom_calendar.git
  

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets :
     - assetss/images/home_purse_icon.png
     - assetss/images/firspage_buy.png
     - assetss/images/slider_inactive.png
     - assetss/images/record_black.png
     - assetss/images/record_blue.png
     - assetss/images/warning_copy.png
     - assetss/images/creating_purse.png
     - assetss/images/tld_icon.png
     - assetss/images/im_bubble.png
     - assetss/images/no_purse_page_icon.png
     - assetss/images/wechat_qrcode.png
     - assetss/images/alipay_qrcode.png
     - assetss/images/no_data.png
     - assetss/images/creat_purse_wait.png
     - assetss/images/purse_success.png
     - assetss/images/sale_button.png
     - assetss/images/icon_buy.png
     - assetss/images/icon_buy_unsel.png
     - assetss/images/icon_sale_unsel.png
     - assetss/images/icon_mission.png
     - assetss/images/icon_mission_unsel.png
     - assetss/images/icon_purse.png
     - assetss/images/icon_purse_unsel.png
     - assetss/images/icon_sale.png
     - assetss/images/icon_sale_unsel.png
     - assetss/images/mission_publish_icon.png
     - assetss/images/icon_message.png
     - assetss/images/icon_message_unsel.png
     - assetss/images/icon_choose_accept.png
     - assetss/images/icon_choose_mission.png
     - assetss/images/icon_choose_rank.png
     - assetss/images/icon_find.png
     - assetss/images/icon_find_unsel.png
     - assetss/images/rank_back.png
     - assetss/images/icon_acceptance_bill.png
     - assetss/images/icon_acceptance_bill_unsel.png
     - assetss/images/icon_acceptance_invite.png
     - assetss/images/icon_acceptance_invite_unsel.png
     - assetss/images/icon_acceptance_mine.png
     - assetss/images/icon_acceptance_mine_unsel.png
     - assetss/images/icon_acceptance_order.png
     - assetss/images/icon_acceptance_order_unsel.png
     - assetss/images/detail_red_packet_bg.png
     - assetss/images/unfinished_red_envelope.png
     - assetss/images/finished_red_envelope.png
     - assetss/images/red_denvelope_qrcode.png
     - assetss/images/unopen_red_envelope.png
     - assetss/images/red_envelope_icon.png
     - assetss/images/game_icon.png
     - assetss/images/aaa_person_center_unsel.png
     - assetss/images/aaa_person_center.png
     - assetss/images/icon_friend_team.png
     - assetss/images/icon_friend_team_unsel.png
     - assetss/images/aaa_user_header.png
     - assetss/images/normal_red_envelope.png
     - assetss/images/promotion_red_envelope.png
     - assetss/images/promotion_red_envelope_qrcode.png
     - assetss/images/icon_promotion.png
     - assetss/images/ylb_balance_sel.png
     - assetss/images/ylb_balance_unsel.png
     - assetss/images/ylb_recorder_sel.png
     - assetss/images/ylb_recorder_unsel.png
     - assetss/images/icon_aaa_plus_star_unsel.png
     - assetss/images/icon_aaa_plus_star.png
     - assetss/images/white_logo.png
     - assetss/images/first_purse_bottom.png
     - assetss/images/purse_detail_bg.png
     - assetss/images/my_purse_exchange.png
     - assetss/images/my_purse_get_money.png
     - assetss/images/my_purse_scan.png
     - assetss/images/find_bg.png
     - assetss/images/have_logo_bg.png
     - assetss/images/no_mission.png
     
    

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

  fonts :
      - family : appIconFonts
        fonts : 
         - asset : assetss/fonts/iconfont.ttf